config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'home/index'

  root to: "home#index"

  resources :jobs

  resources :chats

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord

    belongs_to :user

end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_devise_params, if: :devise_controller?

  def configure_devise_params
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :rol, :email, :password, :password_confirmation)
    end
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

    def index
        @chats = Chat.all
    end

    def new
    end

    def create
        @chat = Chat.new chat_params
        @chat.save

        redirect_to @chat
    end

    def show
        @chat = Chat.find params[:id]
    end

    private
    def chat_params
        params.require(:chat).permit :topic
    
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

    def index
        @jobs = Job.where user_id: current_user.id
    end

    def new
    end

    def create
        #render plain: params[:job].inspect
        #@job = Job.new job_params

        @job = current_user.jobs.new job_params

        @job.save

        redirect_to @job
    end

    def show
        @job = Job.find params[:id]
    end

    private
    def job_params
        params.require(:job).permit :name, :description, :paymentAmount, :ubication
    
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/_chat.html.erb
<%= chat.topic %> <br>

<br>
<br>

app/views/chats/index.html.erb
<%= render @chats %>

app/views/chats/new.html.erb
<p>Hola desde mi vista</p>

<%= form_for :chat, url: chats_path do |f| %>
    <%= f.label :topic %> 
    <%= f.text_field :topic %> <br>

    <%= f.submit %>

<% end %>

app/views/chats/show.html.erb
<%= @chat.topic%>

app/views/home/index.html.erb
<% if user_signed_in? %>
    <h1>Bienvenido <%= current_user.name %> </h1>
<% else%>
    <h1>Bienvenido a Little jobs</h1>
<% end %>

app/views/jobs/_job.html.erb
<%= job.name %> <br>
<%= job.description %> <br>
<%= job.paymentAmount %> <br>
<%= job.ubication %>

<br>
<br>

app/views/jobs/index.html.erb
<%= render @jobs %>

app/views/jobs/new.html.erb
<p>Hola desde mi vista</p>

<%= form_for :job, url: jobs_path do |f| %>
    <%= f.label :name %> 
    <%= f.text_field :name %> <br>

    <%= f.label :description %> 
    <%= f.text_field :description %> <br>

    <%= f.label :paymentAmount %>
    <%= f.text_field :paymentAmount %> <br>

    <%= f.label :ubication %>
    <%= f.text_field :ubication %> <br>

    <%= f.submit %>

<% end %>

app/views/jobs/show.html.erb
<%= @job.name%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LittleJobs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <ul class="nav justify-content-end">

      <%- if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
        </li>

        <% else %>

        <li class="nav-item">
          <%= link_to 'Login', new_user_session_path %>
        </li>

        <li class="nav-item">
          <%= link_to 'Registrarse', new_user_registration_path %>
        </li>

      <% end %>

    </ul>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>